config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :recipes
  resources :cuisines
  resources :recipe_types, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes

  #validates_presence_of :nome, message: "deve ser preenchido"
  validates :name, presence: true, uniqueness: true, length: {maximum: 50}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  validates :title, :recipe_type, :difficulty, :cook_time, :ingredients, :method, presence: true
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipe

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    id = params[:id]
    @cuisine = Cuisine.find id
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    #cuisine_params = params.require(:cuisine).permit(:name)
    #@cuisine = Cuisine.new(cuisine_params)
    name = params[:cuisine][:name]
    @cuisine = Cuisine.new(name: name)

    if @cuisine.save
      #redirect_to cuisine_path @cuisine.id
      #redirect_to cuisine_path @cuisine
      redirect_to @cuisine
      #redirect_to root_path
    else
      flash[:notice] = 'Você deve informar o nome da cozinha'
      #render :new   #Não pode dar redirect, o render só reendeniza a view e não perde os valores das variáveis
      render :new
    end

    #@exception = cuisine.errors.message
#    @exception = cuisine.errors.details[:name]
#    puts @exception.erros.any?
    #puts @exception


  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cuisines = Cuisine.all
    @recipes = Recipe.all
    @recipe_types = RecipeType.all
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def new
    @recipe_type = RecipeType.new
  end

  def create
    name = params[:recipe_type][:name]
    #recipe_type_params = params.require(:recipe_type).permit(:name)
    @recipe_type = RecipeType.new(name: name)

    if @recipe_type.save
      redirect_to @recipe_type
    else
      flash[:notice] = 'Você deve informar o nome do tipo de receita'
      render :new
    end
  end

  def show
    @recipe_type = RecipeType.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    id = params[:id]
    @recipe = Recipe.find id
  end

  def new
    @recipe = Recipe.new
  end

  def create
    #Forma mais segura de pegar os parâmetros, para evitar que alguém envie parâmetros que não existem.
    #recipe_params = params.require(:recipe).permit(:title, :recipe_type, :cuisine,
    #	:cook_time, :ingredients, :method)
    #@recipe = Recipe.new(recipe_params)
    #recipe.save
    #redirect_to recipe_path recipe.id

=begin
    #OU

    recipe = params[:recipe]
    titulo = recipe[:title]
    tipo = recipe[:recipe_type]
    cozinha = recipe[:cuisine_id]
    dificuldade = recipe[:difficulty]
    tempo = recipe[:cook_time]
    ingredientes = recipe[:ingredients]
    preparo = recipe[:method]

    recipe = Recipe.new(title: titulo, recipe_type: tipo, cuisine_id: cozinha, difficulty: dificuldade,
          cook_time: tempo, ingredients: ingredientes, method: preparo)
=end

    recipe_params = params.require(:recipe).permit(:title, :cuisine_id,
      :recipe_type_id, :cook_time, :ingredients, :method, :difficulty)
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      #redirect_to recipe_path recipe   OU
      redirect_to recipe_path @recipe.id
    else
      flash[:notice] = 'Você deve informar todos os dados da receita'
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/_form.html.erb
<%= form_for @cuisine do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <p><%= flash[:notice] %></p>
  <%= f.submit button_name %>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Editar Cozinha</h1>
<% @cuisine.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
<%= render  partial: "form", locals: { button_name: 'Salvar'} %>

app/views/cuisines/new.html.erb
<%= flash[:notice]%>

<%= form_for(@cuisine) do |f| %>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  <%= f.submit 'Enviar'%>
<% end %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>
<% if @cuisine.recipes.any? %>
  <%@cuisine.recipes.each do |recipe|%>
    <h1><%= recipe.title %></h1>
    <ul>
      <li><%= recipe.recipe_type.name %></li>
      <li><%= recipe.cuisine.name %></li>
      <li><%= recipe.difficulty %></li>
      <li><%= recipe.cook_time%> minutos</li>
    </ul>
  <%end%>
<%else%>
  Nenhuma receita encontrada para este tipo de cozinha
<%end%>

app/views/home/index.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<%=link_to "Enviar uma receita", new_recipe_path%>
</br>
<%=link_to "Cadastrar uma cozinha", new_cuisine_path%>
</br>
<div>
  <%count = 0%>
  Cozinhas:
  <% @cuisines.each do |cuisine| %>
    <%= link_to cuisine.name, cuisine_path(cuisine.id) %>
    <%= " | " if @cuisines.count > count+= 1 %>
  <% end %>
</div>
</br>
<div>
  <%count = 0%>
  Tipo de Receitas:
  <% @recipe_types.each do |recipe_type| %>
    <%= link_to recipe_type.name, recipe_type_path(recipe_type.id) %>
    <%= " | " if @recipe_types.count > count+= 1 %>
  <% end %>
</div>

<%@recipes.each do |recipe|%>
  <h1><%=link_to(recipe.title, recipe_path(recipe.id))%></h1>
  <ul>
    <li><%=recipe.recipe_type.name%></li>
    <li><%=recipe.cuisine.name%></li>
    <li><%=recipe.difficulty%></li>
    <li><%=recipe.cook_time%> minutos</li>
  </ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipe_types/new.html.erb
<%= flash[:notice] %>

<%= form_for (@recipe_type) do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>
<% if @recipe_type.recipe.any? %>
  <%@recipe_type.recipe.each do |recipe|%>
    <h1><%= recipe.title %></h1>
    <ul>
      <li><%= recipe.recipe_type.name%></li>
      <li><%= recipe.cuisine.name%></li>
      <li><%= recipe.difficulty%></li>
      <li><%= recipe.cook_time%> minutos</li>
    </ul>
  <%end%>
<% else %>
  Nenhuma receita encontrada para este tipo de receitas
<% end %>

app/views/recipes/edit.html.erb
<%= form_for @recipe do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select :recipe_type_id, RecipeType.all, :id, :name%>
  </div>
  <div>
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select :cuisine_id, Cuisine.all, :id, :name %>
  </div>
  <div>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients %>
  </div>
  <div>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_area :method %>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/recipes/new.html.erb
<%= flash[:notice]%>

<%= form_for Recipe.new do |f| %>
  <div>
    <%= f.label :title, "Título" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type_id, "Tipo da Receita" %>
    <%= f.collection_select(:recipe_type_id, RecipeType.all, :id, :name) %>
  </div>
  <div>
    <%= f.label :cuisine_id, "Cozinha" %>
    <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :name) %>
  </div>
  <div>
    <%= f.label :difficulty, "Dificuldade" %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time, "Tempo de Preparo" %>
    <%= f.text_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, "Ingredientes" %>
    <%= f.text_field :ingredients %>
  </div>
  <div>
    <%= f.label :method, "Como Preparar" %>
    <%= f.text_field :method %>
  </div>
  <%= f.submit "Enviar" %>
<% end %>

app/views/recipes/search.html.erb
<h1>Resultado da busca por: <%= @search %></h1>
<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/recipes/show.html.erb
<h1><%=@recipe.title%></h1>
<h3>Detalhes</h3>
<%=link_to("Voltar", root_path)%>
</br>
<ul>
  <li>
    <p><%=@recipe.recipe_type.name%></p>
  </li>
</ul>
<p><%=@recipe.cuisine.name%></p>
<p><%=@recipe.difficulty%></p>
<p><%="#{@recipe.cook_time} minutos"%></p>
<!--Ou<p><%=@recipe.cook_time%> minutos</p>-->
</br>
<h3>Ingredientes</h3>
<p><%=@recipe.ingredients%></p>
</br>
<h3>Como Preparar</h3>
<p><%=@recipe.method%></p>

app/views/shared/_search.html.erb
<%= form_tag(search_recipes_path, method: :get) do%>
  <%= label_tag(:search, 'Busca')%>
  <%= text_field_tag :search %>

  <%= submit_tag 'Buscar'%>
<% end %>